name: Subir la API a Docker Hub (receta reutilizable)

on:
  workflow_call:
    inputs:
      image-name:
        description: Nombre de la imagen Docker
        required: true
        type: string

      image-tag:
        description: Tag de la imagen
        required: true
        type: string

      k3s-server-public-ip:
        description: IP pública del servidor K3S
        required: true
        type: string

      environment:
        description: Ambiente de despliegue
        required: true
        type: string

      namespace:
        description: Namespace de Kubernetes
        required: true
        type: string

      env-vars:
        description: Variables de entorno dinámicas (formato KEY=VALUE separadas por espacio)
        required: false
        type: string
        default: ""

    secrets:
      DOCKER_USERNAME:
        required: true

      DOCKER_PASSWORD:
        required: true

      EA2_SSH_PRIVATE_KEY:
        required: true

  workflow_dispatch:
    inputs:
      image-name:
        description: Nombre de la imagen
        required: true
        type: string

      image-tag:
        description: Tag de la imagen
        required: true
        type: string

      k3s-server-public-ip:
        description: IP pública del servidor
        required: true
        type: string

      environment:
        description: Ambiente
        required: true
        type: string
        default: production

      namespace:
        description: Namespace Kubernetes
        required: true
        type: string
        default: default

      env-vars:
        description: Variables de entorno dinámicas (formato KEY=VALUE separadas por espacio)
        required: false
        type: string
        default: ""

jobs:

  deps-and-test:
    name: Dependencies and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

  build-and-push:
    name: Build and Push Docker
    needs: deps-and-test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ inputs.image-name }}

          docker build \
            -t $IMAGE:${{ inputs.image-tag }} \
            -t $IMAGE:latest .

      - name: Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ inputs.image-name }}

          docker push --all-tags $IMAGE

  deploy-to-k8s:
    name: Deploy to K3S
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EA2_SSH_PRIVATE_KEY }}

      - name: Verificar conexión
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
          ubuntu@${{ inputs.k3s-server-public-ip }} "echo Conexion correcta"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Copiar manifiestos
        run: |

          ssh -o StrictHostKeyChecking=accept-new \
          ubuntu@${{ inputs.k3s-server-public-ip }} \
          "sudo rm -rf /tmp/k8s-deploy"

          scp -o StrictHostKeyChecking=accept-new \
          -r k8s \
          ubuntu@${{ inputs.k3s-server-public-ip }}:/tmp/k8s-deploy

      - name: Crear Namespace
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
          ubuntu@${{ inputs.k3s-server-public-ip }} \
          "sudo k3s kubectl create namespace ${{ inputs.namespace }} --dry-run=client -o yaml | sudo k3s kubectl apply -f -"

      - name: Aplicar manifiestos
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
          ubuntu@${{ inputs.k3s-server-public-ip }} \
          "sudo k3s kubectl apply -n ${{ inputs.namespace }} -f /tmp/k8s-deploy"

      - name: Actualizar imagen
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
          ubuntu@${{ inputs.k3s-server-public-ip }} \
          "sudo k3s kubectl set image deployment/demo-api demo-api=${{ secrets.DOCKER_USERNAME }}/${{ inputs.image-name }}:${{ inputs.image-tag }} -n ${{ inputs.namespace }}"

      - name: Inyectar variables de entorno
        if: inputs.env-vars != ''
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
          ubuntu@${{ inputs.k3s-server-public-ip }} \
          "sudo k3s kubectl set env deployment/demo-api ${{ inputs.env-vars }} -n ${{ inputs.namespace }}"

      - name: Esperar Rollout
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
          ubuntu@${{ inputs.k3s-server-public-ip }} \
          "sudo k3s kubectl rollout status deployment/demo-api -n ${{ inputs.namespace }} --timeout=120s"

      - name: Rollback Automático
        if: failure()
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
          ubuntu@${{ inputs.k3s-server-public-ip }} \
          "sudo k3s kubectl rollout undo deployment/demo-api -n ${{ inputs.namespace }}"

      - name: Esperar Rollback
        if: failure()
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
          ubuntu@${{ inputs.k3s-server-public-ip }} \
          "sudo k3s kubectl rollout status deployment/demo-api -n ${{ inputs.namespace }} --timeout=120s"
