name: EA3 - Comandos manuales k3s

on:
  workflow_dispatch:
    inputs:
      comando:
        description: "Comando kubectl a ejecutar (sin 'kubectl', ej: get pods -o wide)"
        required: true
        type: string

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Debug variable
        run: echo "IP es -> [${{ vars.K3S_SERVER_PUBLIC_IP }}]"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EA2_SSH_PRIVATE_KEY }}

      - name: Ejecutar comando en el cluster
        run: |
          ssh -o StrictHostKeyChecking=accept-new ubuntu@${{ vars.K3S_SERVER_PUBLIC_IP }} \
            "sudo k3s kubectl ${{ inputs.comando }}"
